alert("¡Soy JavaScript!"); // ACÁ SE HACE UNA ALERTA EN LA WEB, EN UN SOLO PARRAFO.

alert('Hello');
alert('World');

 /* ACÁ SE HACE UNA ALERTA DE LA MISMA FORMA,
  PERO ÉSTA ALERTA SALE EN DOS PARRAFOS DIFERENTES, PRIMERO SALE "HELLO" Y LUEGO SALE "WORLD" */

